version: "3.0"

scanning-settings:
  max-depth: 6
  exclude: []
  include-files: []
  system:
    targets: []

report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:
        environment-results: true
        unpinned-requirements: true
      cvss-severity: []
      vulnerabilities:
        70612:
          reason: We are not impacted by this vulnerability
          expires: "2025-05-15"

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - critical
      exploitability:
        - critical

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch
