name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Python dependencies
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Security scanning with Bandit (Python security linter)
      - name: Run Bandit security scan
        run: |
          pip install bandit
          bandit -r .

      # Dependency scanning with Safety
      - name: Run Safety scan for dependencies
        run: |
          pip install safety
          safety check -i 70612

      # Linting with Flake8 (to enforce code quality best practices)
      - name: Lint code with Flake8
        run: |
          pip install flake8
          flake8 .
